# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Massenger_clone' do
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'



end
